### ISSUE TITLE
mx versions of cekit image not matching mx versions required by graal

### ISSUE THREAD

**Issue by zakkak** [mandrel/mandrel-packaging#10]
`cekit/mx/add-mx.sh` defines the versions of mx to be installed in `/opt/mx` and `src/build.java` gets the required mx version by inspecting the `suite.py` files in the graal sources.

The mx versions in the graal sources are expected to change often, thus requiring manually updating cekit (and rebuilding our images). It would be nice if we could automate this.

**Comment by zakkak** [comment]
Thoughts:

* `build.java` should not use the specific (minimum required) mx version that is specified in the `suite.py` files. It should just expect mx to be available in `/tmp/mx`
* In `cekit/mx/add-mx.sh` we should install a single version of `mx` (the latest we have tested, CI to the rescue)
* When updating graal we need to ensure that the `mx version` in `cekit` is still OK (CI to the rescue)

**Comment by galderz** [comment]
@zakkak This should now be fixed in the code. Cekit installs a single mx version and that's used in the script. There's no more checking the mx version.

**Comment by zakkak** [comment]
Fixed in #14
